### PR TITLE
Fix permission isue and added checksum validation

### LINKED ISSUE #5: Missing list permissions
Due to missing list permissions the cleanup is not working

### LINKED ISSUE #6: Added checksum validation for aws-nuke binary
Added checksum validation for aws-nuke binary

Reason:

Hackers could gain access to the GitHub repo of aws-nuke and replace the binary by an evil bot. By the validation we make sure we always get the expected binary.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #5
Closes #6

### CODE REVIEW

File: src/main/java/com/exasol/ciisolation/aws/cleanup/AwsAccountCleanerBuildSpec.java [hunk 1]
```diff
@@ -32,6 +32,7 @@
         return new String[] { getWriteToFileCommand(getAwsNukeConfig(), AWS_NUKE_CONFIG), //
                 "cat aws-nuke-config.yml", //
                 "wget -q https://github.com/rebuy-de/aws-nuke/releases/download/v2.15.0/aws-nuke-v2.15.0-linux-amd64.tar.gz -O aws-nuke.tar.gz", //
+                "echo \"7d8b50fec337a546e22d1d4d0a2fd3363f140f38  aws-nuke.tar.gz\" | shasum -c",
```
Comment (morazow) [inline src/main/java/com/exasol/ciisolation/aws/cleanup/AwsAccountCleanerBuildSpec.java:35]: This would have to change with each update. Unfortunately, the aws-nuke artifacts do not have corresponding checksum in the assets list. Then you could download both of them.

**Review by morazow — APPROVED** [review]

File: src/main/java/com/exasol/ciisolation/aws/cleanup/AwsAccountCleanerBuildSpec.java (hunk 1 above)
Comment (morazow) [reply src/main/java/com/exasol/ciisolation/aws/cleanup/AwsAccountCleanerBuildSpec.java:35]: Yes, that is good point. 

Still when you update the version you get the shasum from downloaded artifact. More secure variant would be gpg signature checks using developers keys in addition to checksum checks. An example using gpg keys [here](https://github.com/morazow/docker-nginx/blob/main/Dockerfile#L79-L83).

Comment (jakobbraun) [reply src/main/java/com/exasol/ciisolation/aws/cleanup/AwsAccountCleanerBuildSpec.java:35]: yea. That would be great. But at the moment, I think it's ok like that.
